### ISSUE TITLE
Add support for "soft" delete

### ISSUE THREAD

**Issue by mfriesen** [formkiq/formkiq-core#189]
Add the ability to "soft" delete a document / restore document.

API(s)
DELETE /documents/{documentId}?softDelete=true
PUT /documents/{documentId}?restoreDelete=true
GET /documents?showDeleted <-- List Deleted documents

Questions:
1) I assume the only way to see a "deleted" document is through GET /documents?showDeleted otherwise the document will disappear from all other searches.

**Comment by reganwolfrom** [comment]
@mfriesen this looks good, but a few comments:

1. for the restore, I'd recommend this endpoint: `PUT /documents/{documentID}/restore`
2. I think `showDeleted` sounds like it will include deleted in the results such as `GET /documents` and `POST /search`. I wonder if for now, the need for a "trash bin" should use `GET /documents?deleted=true` or `GET /documents?status=softDeleted`. I like the idea of `deleted=true` for now, rather than implementing status at the moment.
