### ISSUE TITLE
Create endpoint to access attribute allowed values: GET /attributes/{key}/allowedValues

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#243]
GET /attributes/{attributeKey}/allowedValues?classificationId={classificationId}&locale={isoLocale}&allSchemas={true|false}

For searches, we need to have the user include allSchemas, otherwise we will show only the site schema or provided classification schema (+ site schema).

NOTE: we won't be including locale at this point, using a "default" locale for now.

We want to return the `value` plus a human-readable `label` that could eventually reflect different specified locales.

```
{
  'allowedValues': [
    {
      'value': 'A',
      'label': 'Aardvark'
    },
   {
      'value': 'B',
      'label': 'Buffalo'
   }
  ]
}
```

NOTE: if two classifications have the same allowed value, the localized value MUST BE THE SAME; workaround would be to have differentiated allowed values, e.g., 'poNumberInvoice' and 'poNumberSalesQuote'

**Comment by mfriesen** [comment]
We discussed returning instead
{
	"allowedValues":[
		"A","B", "C"
	],
	"locale":{
		"en":{
			"A":"AAAAA",
			"B":"BBBBB",
			"C":"CCCCC"
		}
	}
}

**Comment by mfriesen** [comment]
Attribute Allowed values aren't under the /attributes but under schema/classification. Maybe instead of

GET /attributes/{attributeKey}/allowedValues

it should be
GET /sites/{siteId}/schema/{attributeKey}/allowedValues
GET /sites/{siteId}/classifications/{classificationId}/{attributeKey}/allowedValues

maybe 
GET /attributes/{attributeKey}/allowedValues would retrieve all of them?
